language: ruby
cache: bundler
rvm:
  - 2.3.0
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - chromedriver

env:
  - TESTFOLDER=spec/features/community_leader
  - TESTFOLDER=spec/features/visitor
  - TESTFOLDER=spec/features/registered_user
  - TESTFOLDER=spec/requests
  - TESTFOLDER=spec/mailers
  - TESTFOLDER=spec/features/admin
  - TESTFOLDER=spec/features/pending_user
  - TESTFOLDER=spec/models
script:
  - bundle exec rails db:test:prepare
  - bundle exec rspec $TESTFOLDER -p

before_install:
  - brew update
  - brew install chromedriver
before_script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate

notifications:
  email: false

  slack:
    secure: Zudw4uA4rsKkKoS67I7bYFMcE/X9vgSYa0Syf/gt2vPbfJ5zwp1RSOZHevnaSlyVizrx2Lli66BoT+VfzFK1Xv5lD7iAsYCLCw37gfRI9IrzlAKr2y2CeZ5+Ym/8onyhP1Zn08A2yuGWlMIzUWuGb+QNCsBj78uENnLHchLoSPuMHUJMgqKBYfLmG/jywrWP1gp3ZtfX+qbdhKK2Yz8mGaz8vkOSDtKl2LaaceD4oZDpNmX7aIrxha0NYXUoMoz/8vhe+3mzcKHTwZDsNRUFcHNesTk22NHRTx1lMrvTHDGu0MLgEzggzU2T50pzpgYQQi0lLLG4sFkmfPdlPFs2oMhAsAuOGeeKd3bENlLIClcKLngMNtMJsvXs5Pqdrwt3Uiz+W/KZagPe0oTbl+RCARyYs/KgmffLDcGs5NqRz9vlfRC1iPzH36k9ui4fCZo8vbTIIkDyno6LzbwDlG9m60F13LkQL80KBTdi6g1tQ+v5LIgxLdMzfrJfnnFk+ZYicduGiXslmbsjPRHoHEu2ecIQagUQsUYGKWepGAQuwkE8BEstYtiBDy04Y1ITIwJ4/mwA+MGiRndx8EtEXZGhiZuVHvA/4Wii8QQwSDkV7ng8iRm6yHKD0D1g+KL+kUBXNEGcnsrBXW5EjOIBqzSup006PwPAB1w4dLgjf92I21k=
