language: ruby
cache: bundler
sudo: required
dist: trusty
rvm:
  - 2.3.1
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver

env:
  - TESTFOLDER=spec/features/community_leader
  - TESTFOLDER=spec/features/registered_user
  - TESTFOLDER=spec/requests
  - TESTFOLDER=spec/mailers
  - TESTFOLDER=spec/features/admin
  - TESTFOLDER=spec/features/pending_user
  - TESTFOLDER=spec/models
  - TESTFOLDER=spec/features/visitor
script:
  - bundle exec rails db:test:prepare
  - bundle exec rspec $TESTFOLDER -p

before_script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

notifications:
  email: false

  slack:
    secure: ENV['slack_key']
